piggybank/src/main/java/cz/filek/pia/model/Card.java
package cz.filek.pia.model;

import javax.persistence.*;
import java.sql.Date;

/**
 * Entity for bank cards
 *
 * @author Filip Jani
 */
@Entity
@Table(name = "card")
public class Card
{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int id;

    @Column(name = "number", length = 16)
    private String number;

    @Column(name = "valid_from")
    private Date validFrom;

    @Column(name = "valid_to")
    private Date validTo;

    @Column(name = "cvv", length = 3)
    private String cvv;

    @Column(name = "is_blocked")
    private boolean isBlocked;

    @OneToOne
    @JoinColumn(name = "account_id")
    private Account account;

    /**
     * Returns card id
     * @return int
     */
    public int getId()
    {
        return id;
    }

    /**
     * Setter for ID
     * @param id int
     */
     public void setId(int id)
     {
     this.id = id;
     }

    /**
     * Returns card number as a string
     * @return String
     */
    public String getNumber()
    {
        return number;
    }

    /**
     * Setter for card number
     * @param number String
     */
    public void setNumber(String number)
    {
        this.number = number;
    }

    /**
     * Returns card's valid from date
     * @return Date
     */
    public Date getValidFrom()
    {
        return validFrom;
    }

    /**
     * Setter for card's valid from date
     * @param validFrom Date
     */
    public void setValidFrom(Date validFrom)
    {
        this.validFrom = validFrom;
    }

    /**
     * Returns card's valid to date
     * @return Date
     */
    public Date getValidTo()
    {
        return validTo;
    }

    /**
     * Setter for card's valid to date
     * @param validTo Date
     */
    public void setValidTo(Date validTo)
    {
        this.validTo = validTo;
    }

    /**
     * Returns card's CVV code
     * @return String
     */
    public String getCvv()
    {
        return cvv;
    }

    /**
     * Setter for card's CVV
     * @param cvv String
     */
    public void setCvv(String cvv)
    {
        this.cvv = cvv;
    }

    /**
     * Returns true if card is blocked
     * @return boolean
     */
    public boolean isBlocked()
    {
        return isBlocked;
    }

    /**
     * Setter for card status
     * @param blocked boolean
     */
    public void setBlocked(boolean blocked)
    {
        isBlocked = blocked;
    }

    /**
     * Returns Account entity
     * @return Account
     */
    public Account getAccount()
    {
        return account;
    }

    /**
     * Setter for Account entity
     * @param account Account
     */
    public void setAccount(Account account)
    {
        this.account = account;
    }

    /**
     * Returns censored card number in format: 4511********1234
     */
    public String getHiddenCardNumber()
    {
        return this.number.substring(0,3) + "********" + this.number.substring(11, number.length() - 1);
    }

    /**
     * Returns if card is valid
     *
     * @return boolean
     */
    public boolean isValid()
    {
        return this.validTo.after(new java.util.Date());
    }

    /**
     * Returns card valid date in formatted String: mm/yy
     *
     * @return String
     */
    public String getValidToMonthYear()
    {
        String year = String.valueOf(this.validTo.toLocalDate().getYear());
        return this.validTo.toLocalDate().getMonth().getValue() + "/" + year.substring(2);
    }
}

piggybank/src/main/java/cz/filek/pia/model/PaymentOrder.java
package cz.filek.pia.model;

import javax.persistence.*;
import java.io.Serializable;
import java.sql.Date;

/**
 * Entity for payment order
 *
 * @author Filip Jani
 */
@Entity
@Table(name = "payment_order")
public class PaymentOrder extends PaymentOrderBasic implements Serializable
{
    @Column(name = "processed_date")
    private Date processedDate;

    @Column(name = "due_date")
    protected Date dueDate;

    @Transient
    private boolean recaptcha;

    /**
     * Default constructor
     */
    public PaymentOrder(){}

    /**
     * Returns PaymentOrder from PaymentOrderTemplate
     * @param paymentOrderTemplate : PaymentOrderTemplate
     */
    public PaymentOrder(PaymentOrderTemplate paymentOrderTemplate)
    {
        this.account = paymentOrderTemplate.account;
        this.amount = paymentOrderTemplate.amount;
        this.benefAccount = paymentOrderTemplate.benefAccount;
        this.benefBankCode = paymentOrderTemplate.benefBankCode;
        this.constSymbol = paymentOrderTemplate.constSymbol;
        this.varSymbol = paymentOrderTemplate.varSymbol;
        this.specSymbol = paymentOrderTemplate.specSymbol;
        this.message = paymentOrderTemplate.message;
        this.dueDate = new Date(new java.util.Date().getTime());
    }

    /**
     * Returns PaymentOrder from StandingOrder
     * @param standingOrder : StandingOrder
     */
    public PaymentOrder(StandingOrder standingOrder)
    {
        this.account = standingOrder.account;
        this.amount = -Math.abs(standingOrder.amount);
        this.benefAccount = standingOrder.benefAccount;
        this.benefBankCode = standingOrder.benefBankCode;
        this.constSymbol = standingOrder.constSymbol;
        this.varSymbol = standingOrder.varSymbol;
        this.specSymbol = standingOrder.specSymbol;
        this.message = standingOrder.message;
        this.dueDate = new Date(new java.util.Date().getTime());
    }

    /**
     * Returns processed date
     * @return Date|null
     */
    public Date getProcessedDate()
    {
        return processedDate;
    }

    /**
     * Setter for processed date
     * @param processedDate Date
     */
    public void setProcessedDate(Date processedDate)
    {
        this.processedDate = processedDate;
    }

    /**
     * Returns due date
     * @return Date
     */
    public Date getDueDate()
    {
        return dueDate;
    }

    /**
     * Setter for due date
     * @param dueDate Date
     */
    public void setDueDate(Date dueDate)
    {
        this.dueDate = dueDate;
    }

    /**
     * Returns abbreviation for month title
     * @return String
     */
    public String getDueDateMonthString()
    {
        switch (this.getDueDate().getMonth())
        {
            case 0:
                return "LED";
            case 1:
                return "ÚNO";
            case 2:
                return "BŘE";
            case 3:
                return "DUB";
            case 4:
                return "KVĚ";
            case 5:
                return "ČVN";
            case 6:
                return "ČVC";
            case 7:
                return "SRP";
            case 8:
                return "ZÁŘ";
            case 9:
                return "ŘÍJ";
            case 10:
                return "LIS";
            case 11:
                return "PRO";
            default:
                return "";
        }
    }

    /**
     * Returns full account number:
     *      - Account number/Bank Code
     *
     * @return String
     */
    public String getFullAccountNumber(){
        return super.getBenefAccount() + "/" + super.getBenefBankCode();
    }

    /**
     * Returns result of recaptcha
     * @return boolean
     */
    public boolean isRecaptcha()
    {
        return recaptcha;
    }

    /**
     * Setter for result of recaptcha
     * @param recaptcha boolean
     */
    public void setRecaptcha(boolean recaptcha)
    {
        this.recaptcha = recaptcha;
    }
}

piggybank/src/main/java/cz/filek/pia/model/User.java
package cz.filek.pia.model;

import javax.persistence.*;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;

/**
 * Entity for user
 *
 * @author Filip Jani
 */
@Entity
@Table(name = "user", schema = "public")
public class User implements Serializable
{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int id;

    @Column(name = "login", nullable = false, length = 32, unique = true)
    private String login;

    @Column(name = "password", nullable = false)
    private String password;

    @Column(name = "email", nullable = false, length = 100, unique = true)
    @NotNull
    @Email(message = "Emailová adresa musí být ve správném formátu.")
    @Size(min = 5, max = 100, message = "Email musí být v rozmezí {min} - {max} znaků.")
    private String email;

    @Column(name = "firstname", nullable = false, length = 30)
    @NotNull
    @Size(min = 2, max = 30, message = "Jméno musí být v rozmezí {min} - {max} znaků.")
    private String firstName;

    @Column(name = "lastname", nullable = false, length = 60)
    @NotNull
    @Size(min = 1, max = 60, message = "Příjmení musí být v rozmezí {min} - {max} znaků.")
    private String lastName;

    @Column(name = "phone_number", nullable = true, length = 9)
    @Size(max = 9, message = "Délka čísla musí být maximálně {max} znaků.")
    private String phoneNumber;

    @Column(name = "pin", nullable = false, length = 11, unique = true)
    @NotNull
    @Size(min = 11, max = 11, message = "Rodné číslo musí mít {max} znaků.")
    private String pin;

    public User(){}

    /**
     * Constructor for user entity
     * @param login login
     * @param password password
     * @param email email
     * @param firstName first name
     * @param lastName last name
     * @param phoneNumber phone number
     */
    public User(String login, String password, String email, String firstName, String lastName, String phoneNumber)
    {
        this.login = login;
        this.password = password;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phoneNumber = phoneNumber;
    }

    /**
     * Returns PK ID
     * @return int
     */
    public int getId()
    {
        return id;
    }

    /**
     * Setter for user's id
     * @param id int
     */
    public void setId(int id)
    {
        this.id = id;
    }

    /**
     * Returns user's login
     * @return String
     */
    public String getLogin()
    {
        return login;
    }

    /**
     * Setter for user's login
     * @param login String
     */
    public void setLogin(String login)
    {
        this.login = login;
    }

    /**
     * Returns user's password
     * @return String
     */
    public String getPassword()
    {
        return password;
    }

    /**
     * Setter for user's password
     * @param password String
     */
    public void setPassword(String password)
    {
        this.password = password;
    }

    /**
     * Returns user's email
     * @return String
     */
    public String getEmail()
    {
        return email;
    }

    /**
     * Setter for user's email
     * @param email String
     */
    public void setEmail(String email)
    {
        this.email = email;
    }

    /**
     * Returns user's first name
     * @return String
     */
    public String getFirstName()
    {
        return firstName;
    }

    /**
     * Setter for user's first name
     * @param firstName String
     */
    public void setFirstName(String firstName)
    {
        this.firstName = firstName;
    }

    /**
     * Returns user's last name
     * @return String
     */
    public String getLastName()
    {
        return lastName;
    }

    /**
     *  Setter for user's last name
     * @param lastName String
     */
    public void setLastName(String lastName)
    {
        this.lastName = lastName;
    }

    /**
     * Returns user's phone number
     * @return String
     */
    public String getPhoneNumber()
    {
        return phoneNumber;
    }

    /**
     * Setter for user's phone number
     * @param phoneNumber String
     */
    public void setPhoneNumber(String phoneNumber)
    {
        this.phoneNumber = phoneNumber;
    }

    /**
     * Returns user's PIN
     * @return String
     */
    public String getPin()
    {
        return pin;
    }

    /**
     * Setter for user's Personal Identification Number
     * @param pin String
     */
    public void setPin(String pin)
    {
        this.pin = pin;
    }

    /**
     * Returns user's full name: firstname lastname
     * @return String
     */
    public String getFullName()
    {
        return this.firstName + " " + this.lastName;
    }
}

piggybank/src/main/java/cz/filek/pia/controller/user/DashboardController.java
package cz.filek.pia.controller.user;

import cz.filek.pia.controller.AuthController;
import cz.filek.pia.model.*;
import cz.filek.pia.services.TransactionsService;
import cz.filek.pia.services.UserService;
import cz.filek.pia.services.interfaces.ITransactionsService;
import cz.filek.pia.services.interfaces.IUserService;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;

import java.util.Collections;
import java.util.List;

/**
 * Controller for clients dashboard
 *
 * @author Filip Jani
 */
@Controller
@RequestMapping(path = "/user", name = "DashboardCtl")
public class DashboardController extends AuthController
{
    private ITransactionsService transactionsService;
    private IUserService userService;

    public DashboardController(TransactionsService transactionsService,
                               UserService userService)
    {
        super(transactionsService, userService);
        this.transactionsService = transactionsService;
        this.userService = userService;
    }

    /**
     * Displays default dashboard for client
     *
     * @return ModelAndView
     */
    @GetMapping(path = "dashboard", name = "dashboard")
    public ModelAndView dashboard()
    {
        ModelAndView modelAndView = new ModelAndView("customer/dashboard/default");
        ModelMap modelMap = modelAndView.getModelMap();
        String userLogin = SecurityContextHolder.getContext().getAuthentication().getName();
        User user = userService.getUserByLogin(userLogin);

        List<AccountTransaction> accountTransactions = transactionsService.getAccountTransactions(this.getUserAccount().getAccount().getId());
        Collections.reverse(accountTransactions);
        modelMap.addAttribute("accountTransactions", accountTransactions);

        List<UserCard> userCards = userService.getUserCards(user.getId());
        modelMap.addAttribute("userCards", userCards);

        return modelAndView;
    }
}

piggybank/src/main/webapp/WEB-INF/views/customer/dashboard/default.jsp
<%@ page contentType="text/html; charset=UTF-8" %>
<%@taglib prefix="t" tagdir="/WEB-INF/tags/" %>
<%@taglib prefix="tc" tagdir="/WEB-INF/tags/customer" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<fmt:setLocale value="cs_CZ" scope="session"/>

<t:layout-customer>
    <jsp:attribute name="title">Přehled účtu</jsp:attribute>

    <jsp:body>
        <t:flash-messages/>
        <div class="row mb-5">
            <!-- Karta s přehledem stavu účtu -->
            <tc:user-card/>

            <!-- Karta s historií transakcí -->
            <div class="col-sm-12 col-md-8 col-lg-9">
                <div class="card">
                    <div class="card-header text-white">
                        <div>Poslední transakce</div>
                    </div>

                    <!-- Každý řádek má tři sloupce: datum, informace a částku -->
                    <div class="card-body">

                        <!-- Tabulka s historii transakcí -->

                        <c:forEach items="${accountTransactions}" var="transaction" varStatus="status">
                            <c:if test="${status.count <= 5}">

                                <c:choose>
                                    <c:when test="${transaction.paymentOrder.account.id != userAccount.getAccount().id}">
                                        <c:set var="fromAccount" value="${transaction.paymentOrder.account.string}"/>
                                        <c:set var="amount" value="${-transaction.paymentOrder.amount}"/>
                                    </c:when>
                                    <c:otherwise>
                                        <c:set var="fromAccount" value="${transaction.paymentOrder.fullAccountNumber}"/>
                                        <c:set var="amount" value="${transaction.paymentOrder.amount}"/>
                                    </c:otherwise>
                                </c:choose>

                                <div class="row row-transactions">
                                    <div class="col-3 col-sm-2 col-md-2 col-lg-2">
                                        <div class="text-bold text-small text-center">${transaction.date.toLocalDate().dayOfMonth}</div>
                                        <div class="text-bold text-small text-center">${transaction.paymentOrder.dueDateMonthString}</div>
                                    </div>
                                    <div class="col-5 col-sm-7 col-md-7 col-lg-8">
                                        <div class="text-bold"><a
                                                href="${s:mvcUrl("TransactionCtl#transactionDetail").arg(0, transaction.id).build()}">${fromAccount}</a>
                                        </div>
                                        <div class="text-small">${transaction.transactionType.getText(transaction.transactionType)}</div>
                                    </div>

                                    <c:choose>
                                        <c:when test="${amount >= 0}">
                                            <c:set var="transactionColor" value=""/>
                                        </c:when>
                                        <c:when test="${amount < 0}">
                                            <c:set var="transactionColor" value="text-danger"/>
                                        </c:when>
                                    </c:choose>

                                    <div class="col-4 col-sm-3 col-md-3 col-lg-2 text-right text-horizontal-center">
                                        <span class="${transactionColor} text-bold"><fmt:formatNumber value="${amount}" type="currency"/></span>
                                    </div>
                                </div>
                            </c:if>
                        </c:forEach>
                    </div>

                    <div class="card-footer">
                        <div class="row">
                            <div class="col-12">
                                <div class="text-small text-center">
                                    <a href="${s:mvcUrl('TransactionCtl#history').build()}">Zobrazit všechny transakce</a>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <!-- Přehled karet -->
        <div class="row">
            <div class="col-sm-12 col-md-4 col-lg-3 mb-2">
                <c:if test="${userCards != null}">
                    <c:set var="card" value="${userCards.get(0).card}"/>
                    <div class="card">
                        <div class="card-header">Platební karta</div>
                        <div class="card-body">
                            <div class="card-text">
                                <h5>${userEntity.fullName}</h5>
                                <span class="text-small text-black-50">${card.hiddenCardNumber}</span>
                            </div>
                        </div>
                        <ul class="list-group list-group-flush text-small">
                            <li class="list-group-item">
                                <div>Vydána k účtu:</div>
                                <div class="float-right">${card.account.string}</div>
                            </li>
                            <li class="list-group-item">
                                <div>Platnost do:</div>

                                <c:set var="validToClass" value="text-danger"/>
                                <c:choose>
                                    <c:when test="${card.isValid()}">
                                        <c:set var="validToClass" value="text-success"/>
                                    </c:when>
                                </c:choose>

                                <div class="float-right ${validToClass} text-bold">${card.getValidToMonthYear()}</div>
                            </li>
                        </ul>
                        <button class="btn btn-outline-primary btn-card-small" disabled><span
                                class="fa fa-cog fa-fw"></span></button>
                    </div>
                </c:if>
            </div>
        </div>

    </jsp:body>
</t:layout-customer>