piggybank/src/main/java/cz/filek/pia/model/Account.java
package cz.filek.pia.model;

import javax.persistence.*;

/**
 * Entity for account
 *
 * @author Filip Jani
 */
@Entity
@Table(name = "account")
public class Account
{

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int id;

    @ManyToOne
    @JoinColumn(name = "bank_code")
    private BankCode bankCode;

    @Column(name = "number", length = 10, unique = true)
    private String number;

    @Column(name = "prefix", length = 4)
    private String prefix;

    /**
     * Returns PK ID
     * @return int
     */
    public int getId()
    {
        return id;
    }

    /**
     * Returns bank code
     * @return BankCode
     */
    public BankCode getBankCode()
    {
        return bankCode;
    }

    /**
     * Setter for bank code
     * @param bankCode BankCode
     */
    public void setBankCode(BankCode bankCode)
    {
        this.bankCode = bankCode;
    }

    /**
     * Returns account number
     * @return String
     */
    public String getNumber()
    {
        return number;
    }

    /**
     * Setter for account number
     * @param number String
     */
    public void setNumber(String number)
    {
        this.number = number;
    }

    /**
     * Returns account number prefix
     * @return String
     */
    public String getPrefix()
    {
        return prefix;
    }

    /**
     * Setter for account number prefix
     * @param prefix String
     */
    public void setPrefix(String prefix)
    {
        this.prefix = prefix;
    }

    /**
     * Returns number of account in format of : prefix-number/bankCode
     * @return
     */
    public String getString()
    {
        return this.prefix == null ? this.number + "/" + this.bankCode.getCode() : this.prefix + "-" + this.number + "/" + this.bankCode.getCode();
    }
}

piggybank/src/main/java/cz/filek/pia/model/PaymentOrder.java
package cz.filek.pia.model;

import javax.persistence.*;
import java.io.Serializable;
import java.sql.Date;

/**
 * Entity for payment order
 *
 * @author Filip Jani
 */
@Entity
@Table(name = "payment_order")
public class PaymentOrder extends PaymentOrderBasic implements Serializable
{
    @Column(name = "processed_date")
    private Date processedDate;

    @Column(name = "due_date")
    protected Date dueDate;

    @Transient
    private boolean recaptcha;

    /**
     * Default constructor
     */
    public PaymentOrder(){}

    /**
     * Returns PaymentOrder from PaymentOrderTemplate
     * @param paymentOrderTemplate : PaymentOrderTemplate
     */
    public PaymentOrder(PaymentOrderTemplate paymentOrderTemplate)
    {
        this.account = paymentOrderTemplate.account;
        this.amount = paymentOrderTemplate.amount;
        this.benefAccount = paymentOrderTemplate.benefAccount;
        this.benefBankCode = paymentOrderTemplate.benefBankCode;
        this.constSymbol = paymentOrderTemplate.constSymbol;
        this.varSymbol = paymentOrderTemplate.varSymbol;
        this.specSymbol = paymentOrderTemplate.specSymbol;
        this.message = paymentOrderTemplate.message;
        this.dueDate = new Date(new java.util.Date().getTime());
    }

    /**
     * Returns PaymentOrder from StandingOrder
     * @param standingOrder : StandingOrder
     */
    public PaymentOrder(StandingOrder standingOrder)
    {
        this.account = standingOrder.account;
        this.amount = -Math.abs(standingOrder.amount);
        this.benefAccount = standingOrder.benefAccount;
        this.benefBankCode = standingOrder.benefBankCode;
        this.constSymbol = standingOrder.constSymbol;
        this.varSymbol = standingOrder.varSymbol;
        this.specSymbol = standingOrder.specSymbol;
        this.message = standingOrder.message;
        this.dueDate = new Date(new java.util.Date().getTime());
    }

    /**
     * Returns processed date
     * @return Date|null
     */
    public Date getProcessedDate()
    {
        return processedDate;
    }

    /**
     * Setter for processed date
     * @param processedDate Date
     */
    public void setProcessedDate(Date processedDate)
    {
        this.processedDate = processedDate;
    }

    /**
     * Returns due date
     * @return Date
     */
    public Date getDueDate()
    {
        return dueDate;
    }

    /**
     * Setter for due date
     * @param dueDate Date
     */
    public void setDueDate(Date dueDate)
    {
        this.dueDate = dueDate;
    }

    /**
     * Returns abbreviation for month title
     * @return String
     */
    public String getDueDateMonthString()
    {
        switch (this.getDueDate().getMonth())
        {
            case 0:
                return "LED";
            case 1:
                return "ÚNO";
            case 2:
                return "BŘE";
            case 3:
                return "DUB";
            case 4:
                return "KVĚ";
            case 5:
                return "ČVN";
            case 6:
                return "ČVC";
            case 7:
                return "SRP";
            case 8:
                return "ZÁŘ";
            case 9:
                return "ŘÍJ";
            case 10:
                return "LIS";
            case 11:
                return "PRO";
            default:
                return "";
        }
    }

    /**
     * Returns full account number:
     *      - Account number/Bank Code
     *
     * @return String
     */
    public String getFullAccountNumber(){
        return super.getBenefAccount() + "/" + super.getBenefBankCode();
    }

    /**
     * Returns result of recaptcha
     * @return boolean
     */
    public boolean isRecaptcha()
    {
        return recaptcha;
    }

    /**
     * Setter for result of recaptcha
     * @param recaptcha boolean
     */
    public void setRecaptcha(boolean recaptcha)
    {
        this.recaptcha = recaptcha;
    }
}

piggybank/src/main/java/cz/filek/pia/controller/user/TransactionController.java
package cz.filek.pia.controller.user;

import cz.filek.pia.config.CaptchaConfig;
import cz.filek.pia.controller.AuthController;
import cz.filek.pia.frontend.FlashMessages;
import cz.filek.pia.frontend.Paginator;
import cz.filek.pia.model.*;
import cz.filek.pia.services.*;
import cz.filek.pia.services.interfaces.*;
import org.apache.catalina.servlet4preview.http.HttpServletRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import javax.validation.Valid;
import java.sql.Date;
import java.util.List;

/**
 * Controller used for managing of transactions
 *
 * @author Filip Jani
 */
@Controller
@RequestMapping(path = "/user", name = "TransactionCtl")
public class TransactionController extends AuthController
{
    private IBankCodeService bankCodeService;
    private IUserService userService;
    private ITransactionsService transactionsService;
    private IPaymentTemplateService paymentTemplateService;
    private IAccountService accountService;
    private CaptchaConfig captchaConfig;
    private ICaptchaService captchaService;

    private final String PAYMENT_ORDER = "paymentOrder";

    public TransactionController(BankCodeService bankCodeService,
                                 UserService userService,
                                 TransactionsService transactionsService,
                                 PaymentTemplateService paymentTemplateService,
                                 AccountService accountService,
                                 CaptchaConfig captchaConfig,
                                 CaptchaService captchaService)
    {
        super(transactionsService, userService);
        this.bankCodeService = bankCodeService;
        this.userService = userService;
        this.transactionsService = transactionsService;
        this.paymentTemplateService = paymentTemplateService;
        this.accountService = accountService;
        this.captchaConfig = captchaConfig;
        this.captchaService = captchaService;
    }

    /**
     * Shows form for submitting new transactions
     *
     * @return ModelAndView
     */
    @GetMapping(path = "/transaction/new", name = "new")
    public ModelAndView newTransaction()
    {
        PaymentOrder paymentOrder = new PaymentOrder();
        paymentOrder.setDueDate(new Date(new java.util.Date().getTime()));

        ModelAndView modelAndView = new ModelAndView("customer/transaction/new", PAYMENT_ORDER, paymentOrder);
        modelAndView.addObject("captchaSite", this.captchaConfig.getSite());
        this.addCommon(modelAndView);

        return modelAndView;
    }

    /**
     * Shows form for submitting new transactions with pre-filled inputs from template by its ID
     *
     * @param id : ID of the template
     * @param ra : RedirectAttributes
     * @return ModelAndView
     */
    @GetMapping(path = "/transaction/new/{id}", name = "newFromTemplate")
    public ModelAndView newTransactionFromTemplate(@PathVariable("id") Integer id, final RedirectAttributes ra)
    {
        if (!this.paymentTemplateService.belongsTemplateToUser(id, this.getUser()))
        {
            FlashMessages.addError(ra, "Šablona nebyla nalezena.");
            return new ModelAndView("redirect:/transaction/new");
        }

        PaymentOrder paymentOrder = new PaymentOrder(this.paymentTemplateService.getPaymentOrderTemplate(id));

        ModelAndView modelAndView = new ModelAndView("customer/transaction/new", PAYMENT_ORDER, paymentOrder);
        modelAndView.addObject("selectedOption", id);
        modelAndView.addObject("captchaSite", this.captchaConfig.getSite());
        this.addCommon(modelAndView);

        return modelAndView;
    }

    /**
     * Handles form for submitting new transactions
     *
     * @param model : PaymentOrder
     * @param result : BindingResult
     * @param ra : RedirectAttributes
     * @return ModelAndView
     */
    @PostMapping(path = "/transaction/new/submit", name = "newSubmit")
    public ModelAndView newTransactionSubmit(@Valid @ModelAttribute(PAYMENT_ORDER) PaymentOrder model,
                                             BindingResult result,
                                             final RedirectAttributes ra,
                                             HttpServletRequest request)
    {
        ModelAndView modelAndView = new ModelAndView("customer/transaction/new");
        modelAndView.addObject("captchaSite", this.captchaConfig.getSite());
        this.addCommon(modelAndView);

        String captchaResponse = request.getParameter("g-recaptcha-response");
        if (!this.captchaService.processResponse(captchaResponse))
        {
            result.rejectValue("recaptcha", "error.userAddress", "Nepodařilo se ověřit captchu. Ujistěte se, že máte povolený JS.");
        }

        if(result.hasErrors())
        {
            return modelAndView;
        }

        Account account = this.getUserAccount().getAccount();
        if (model.getBenefAccount().equals(account.getNumber()) && model.getBenefBankCode().equals(account.getBankCode().getCode()))
        {
            FlashMessages.addError(modelAndView, "Nelze odesílat nové platby na vlastní účet.");
            return modelAndView;
        }

        Integer balance = this.transactionsService.getAccountUsableBalance(account.getId());
        if (model.getAmount() > balance)
        {
            FlashMessages.addError(modelAndView, "Na účtu nemáte dostatek peněz pro uskutečnění této transakce.");
            return modelAndView;
        }

        if (this.transactionsService.saveNewPaymentOrder(model, this.getUserAccount()))
        {
            FlashMessages.addSuccess(ra, "Platba byla přijata ke zpracování.");
        } else
        {
            FlashMessages.addError(ra, "Platbu se nepodařilo provést, opakujte prosím akci později.");
        }

        return new ModelAndView("redirect:/user/dashboard");
    }

    /**
     * Shows transaction detail
     *
     * @param id : ID of the transaction
     * @return ModelAndView
     */
    @GetMapping(path = "/transaction/detail/{id}", name = "transactionDetail")
    public ModelAndView showTransactionDetail(@PathVariable("id") int id)
    {
        ModelAndView modelAndView = new ModelAndView("customer/transaction/detail");
        AccountTransaction accountTransaction = this.transactionsService.getAccountTransaction(id);

        modelAndView.addObject("transaction", accountTransaction);

        return modelAndView;
    }

    /**
     * Shows list with all transactions
     *
     * @param page : current page
     * @param limit : items per page
     * @return ModelAndView
     */
    @GetMapping(path = "/transaction/history", name = "history")
    public ModelAndView showTransactionsHistory(@RequestParam(required = false) Integer page, @RequestParam(required = false) Integer limit){
        ModelAndView modelAndView = new ModelAndView("customer/transaction/history");

        if (page == null)
        {
            page = 1;
        }

        if (limit == null)
        {
            limit = Paginator.getLimits()[0];
        }

        Paginator paginator = new Paginator(page, limit, new Sort(Sort.Direction.DESC, "id"));
        List<AccountTransaction> accountTransactions = this.transactionsService.getAccountTransactions(this.getUserAccount(), paginator);
        paginator.prepareForFrontend(this.transactionsService.getAccountTransactionsCount(this.getUserAccount()));

        modelAndView.addObject("accountTransactions", accountTransactions);
        modelAndView.addObject("paginator", paginator);
        modelAndView.addObject("paginatorUrl", "TransactionCtl#history");

        return modelAndView;
    }


    /**
     * Returns JSON with payment order template, so we can fill form with correct values by AJAX
     *
     * @param accountNumber : ID of the payment order template
     * @return JSON payload
     */
    @GetMapping(path = "/transaction/check-account")
    @ResponseBody
    public boolean doesAccountExist(@RequestParam("number") String accountNumber)
    {
        return this.accountService.doesAccountExist(accountNumber);
    }

    //
    //
    //
    //
    //

    /**
     * Adds bank codes list into the template
     *
     * @param modelAndView ModelAndView
     */
    private void addCommon(ModelAndView modelAndView)
    {
        ModelMap map = modelAndView.getModelMap();

        List<BankCode> bankCodeList = bankCodeService.getBankCodes(true);
        map.addAttribute("bankCodeList", bankCodeList);

        List<UserPaymentTemplate> templates = userService.getUserPaymentTemplates(this.getUser());
        map.addAttribute("templates", templates);
    }
}

piggybank/src/main/webapp/WEB-INF/views/customer/transaction/detail.jsp
<%@ page contentType="text/html; charset=UTF-8" %>
<%@taglib prefix="t" tagdir="/WEB-INF/tags/" %>
<%@taglib prefix="tc" tagdir="/WEB-INF/tags/customer" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<fmt:setLocale value="cs_CZ" scope="session"/>

<t:layout-customer>
    <jsp:attribute name="title">Detail transakce</jsp:attribute>

    <jsp:body>
        <t:flash-messages/>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header text-white">
                        <div>Detail transakce</div>
                    </div>
                    <div class="card-body">

                        <c:choose>
                            <c:when test="${transaction.paymentOrder.account.id != userAccount.getAccount().id}">
                                <c:set var="fromAccount" value="${transaction.paymentOrder.account.string}"/>
                                <c:set var="amount" value="${-transaction.paymentOrder.amount}"/>
                            </c:when>
                            <c:otherwise>
                                <c:set var="fromAccount" value="${transaction.paymentOrder.fullAccountNumber}"/>
                                <c:set var="amount" value="${transaction.paymentOrder.amount}"/>
                            </c:otherwise>
                        </c:choose>

                        <c:choose>
                            <c:when test="${amount >= 0}">
                                <c:set var="transactionColor" value=""/>
                            </c:when>
                            <c:when test="${amount < 0}">
                                <c:set var="transactionColor" value="text-danger"/>
                            </c:when>
                        </c:choose>

                        <!-- Základní přehled jako v historii transakcí -->
                        <div class="row">
                            <div class="col-md-1">
                                <div class="text-bold text-small text-md-center">${transaction.date.toLocalDate().dayOfMonth}</div>
                                <div class="text-bold text-small text-md-center">${transaction.paymentOrder.dueDateMonthString}</div>
                            </div>
                            <div class="col-md-9">
                                <div class="text-bold">${fromAccount}</div>
                                <div class="text-small">${transaction.transactionType.getText(transaction.transactionType)}</div>
                            </div>
                            <div class="col-md-2 text-md-right text-horizontal-center"><span
                                    class="${transactionColor} text-bold">
                                <fmt:formatNumber value="${amount}" type="currency"/>
                            </span>
                            </div>
                        </div>

                        <!-- Variabilní,... symboly -->
                        <hr>
                        <div class="row text-left text-row-detail">
                            <div class="col-md-4">
                                <span class="fa fa-info-circle fa-fw"></span>
                                <span class="text-small">
                                <span class="text-bold">Variabilní symbol: </span>
                                ${transaction.paymentOrder.varSymbol}
                            </span>
                            </div>
                            <div class="col-md-4">
                                <span class="fa fa-info-circle fa-fw"></span>
                                <span class="text-small">
                                <span class="text-bold">Konstantní symbol: </span>
                                ${transaction.paymentOrder.constSymbol}
                            </span>
                            </div>
                            <div class="col-md-4">
                                <span class="fa fa-info-circle fa-fw"></span>
                                <span class="text-small">
                                <span class="text-bold">Specifický symbol: </span>
                                ${transaction.paymentOrder.specSymbol}
                            </span>
                            </div>
                        </div>

                        <!-- Číslo účtu -->
                        <hr>
                        <div class="row text-left text-row-detail">
                            <div class="col-md-3">
                                <span class="fa fa-info-circle fa-fw"></span>
                                <span class="text-bold text-small">Číslo účtu příjemce</span>
                            </div>
                            <div class="col-md-9">
                                <span class="text-small">${transaction.paymentOrder.benefAccount} / ${transaction.paymentOrder.benefBankCode}</span>
                            </div>
                        </div>

                        <!-- Typ platby -->
                        <hr>
                        <div class="row text-left text-row-detail">
                            <div class="col-md-3">
                                <span class="fa fa-credit-card fa-fw"></span>
                                <span class="text-bold text-small">Typ transakce</span>
                            </div>
                            <div class="col-md-9">
                                <span class="text-small">${transaction.transactionType.getText(transaction.transactionType)}</span>
                            </div>
                        </div>

                        <!-- Datum transakce -->
                        <hr>
                        <div class="row text-left text-row-detail">
                            <div class="col-md-3">
                                <span class="fa fa-check fa-fw"></span>
                                <span class="text-bold text-small">Datum transakce</span>
                            </div>
                            <div class="col-md-9">
                                <span class="text-small"><fmt:formatDate pattern="dd. MM. yyyy" value="${transaction.paymentOrder.processedDate}"/></span>
                            </div>
                        </div>

                        <!-- ID transakce -->
                        <hr>
                        <div class="row text-left text-row-detail">
                            <div class="col-md-3">
                                <span class="fa fa-hashtag fa-fw"></span>
                                <span class="text-bold text-small">ID transakce</span>
                            </div>
                            <div class="col-md-9">
                                <span class="text-small">${transaction.id}</span>
                            </div>
                        </div>

                        <!-- Zpráva pro příjemce -->
                        <hr>
                        <div class="row text-left text-row-detail">
                            <div class="col-md-3">
                                <span class="fa fa-comment fa-fw"></span>
                                <span class="text-bold text-small">Zpráva pro příjemce</span>
                            </div>
                            <div class="col-md-9">
                                <span class="text-small">${transaction.paymentOrder.message}</span>
                            </div>
                        </div>

                        <!-- Poznámka -->
                        <hr>
                        <div class="row text-left text-row-detail">
                            <div class="col-md-3">
                                <span class="fa fa-sticky-note fa-fw"></span>
                                <span class="text-bold text-small">Poznámka</span>
                            </div>
                            <div class="col-md-9">
                                <div>
                                    <textarea class="form-control mb-2"></textarea>
                                    <input type="submit" class="btn btn-primary btn-sm float-right" value="Uložit poznámku">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </jsp:body>
</t:layout-customer>

piggybank/src/main/webapp/WEB-INF/views/customer/transaction/history.jsp
<%@ page contentType="text/html; charset=UTF-8" %>
<%@taglib prefix="t" tagdir="/WEB-INF/tags/" %>
<%@taglib prefix="tc" tagdir="/WEB-INF/tags/customer" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<fmt:setLocale value="cs_CZ" scope="session"/>

<t:layout-customer>
    <jsp:attribute name="title">Detail transakce</jsp:attribute>

    <jsp:body>
        <t:flash-messages/>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header text-white">
                        <div>Historie transakcí</div>
                    </div>
                    <div class="card-body">
                        <!-- Tabulka s historii transakcí -->

                        <c:forEach items="${accountTransactions}" var="transaction" varStatus="status">

                                <c:choose>
                                    <c:when test="${transaction.paymentOrder.account.id != userAccount.getAccount().id}">
                                        <c:set var="fromAccount" value="${transaction.paymentOrder.account.string}"/>
                                        <c:set var="amount" value="${-transaction.paymentOrder.amount}"/>
                                    </c:when>
                                    <c:otherwise>
                                        <c:set var="fromAccount" value="${transaction.paymentOrder.fullAccountNumber}"/>
                                        <c:set var="amount" value="${transaction.paymentOrder.amount}"/>
                                    </c:otherwise>
                                </c:choose>

                                <div class="row row-transactions">
                                    <div class="col-3 col-sm-2 col-md-1 col-lg-1">
                                        <div class="text-bold text-small text-center">${transaction.date.toLocalDate().dayOfMonth}</div>
                                        <div class="text-bold text-small text-center">${transaction.paymentOrder.dueDateMonthString}</div>
                                    </div>
                                    <div class="col-5 col-sm-7 col-md-7 col-lg-8">
                                        <div class="text-bold"><a
                                                href="${s:mvcUrl("TransactionCtl#transactionDetail").arg(0, transaction.id).build()}">${fromAccount}</a>
                                        </div>
                                        <div class="text-small">${transaction.transactionType.getText(transaction.transactionType)}</div>
                                    </div>

                                    <c:choose>
                                        <c:when test="${amount >= 0}">
                                            <c:set var="transactionColor" value=""/>
                                        </c:when>
                                        <c:when test="${amount < 0}">
                                            <c:set var="transactionColor" value="text-danger"/>
                                        </c:when>
                                    </c:choose>

                                    <div class="col-4 col-sm-3 col-md-3 col-lg-3 text-right text-horizontal-center">
                                        <span class="${transactionColor} text-bold"><fmt:formatNumber value="${amount}" type="currency"/></span>
                                    </div>
                                </div>
                        </c:forEach>
                        <hr>
                        <tc:paginator/>
                    </div>
                </div>
            </div>
        </div>
    </jsp:body>
</t:layout-customer>